export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>TripApp</title>
  <base href="/assingment/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">@charset "UTF-8";.trip-inputs[_ngcontent-ng-c4020560623]{display:flex;gap:10px;margin-bottom:20px}.timeline[_ngcontent-ng-c4020560623]{display:flex;align-items:flex-end;gap:30px;flex-wrap:nowrap;overflow-x:auto;padding:30px 0}.segment[_ngcontent-ng-c4020560623]{display:flex;flex-direction:column;align-items:center;position:relative}.circle[_ngcontent-ng-c4020560623]{width:10px;height:10px;border-radius:50%;background-color:#444}.circle.blue[_ngcontent-ng-c4020560623]{background-color:#007bff}.circle.orange[_ngcontent-ng-c4020560623]{background-color:orange}.circle.purple[_ngcontent-ng-c4020560623]{background-color:#5a5aa5}.circle.end[_ngcontent-ng-c4020560623]{background-color:#aaa}.line[_ngcontent-ng-c4020560623]{width:60px;height:2px;margin:8px 0;background-color:#aaa;position:relative}.line.arrow[_ngcontent-ng-c4020560623]:after{content:"\\2192";position:absolute;right:-14px;top:-8px;color:#000;font-size:14px}.line.level-1[_ngcontent-ng-c4020560623]{background-color:#5a5aa5}.line.curve-up[_ngcontent-ng-c4020560623]{width:60px;height:30px;border-top:2px solid orange;border-radius:40px 40px 0 0;margin-top:-10px}.line.curve-down[_ngcontent-ng-c4020560623]{width:60px;height:30px;border-bottom:2px solid orange;border-radius:0 0 40px 40px;margin-bottom:-10px}.label[_ngcontent-ng-c4020560623]{font-size:12px;margin-top:4px;color:#444}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["input","compositionstart","compositionend","click"],["blur"]);</script>
  <app-root ng-version="19.2.6" ngh="1" ng-server-context="ssg"><app-trip-visualizer _nghost-ng-c4020560623 ngh="0"><div _ngcontent-ng-c4020560623 class="trip-inputs"><input _ngcontent-ng-c4020560623 type="text" placeholder="Start Point" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><input _ngcontent-ng-c4020560623 type="text" placeholder="End Point" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><button _ngcontent-ng-c4020560623 jsaction="click:;">Add Trip</button><button _ngcontent-ng-c4020560623 jsaction="click:;">Reset</button></div><div _ngcontent-ng-c4020560623 class="timeline"><!----></div></app-trip-visualizer></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-AOGSDHQA.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"8":"t0"},"c":{"8":[]}},{}]}</script></body></html>`;